"""add_kpi_snapshots

Revision ID: ed9308d6cbfa
Revises: e66fe5abb7cc
Create Date: 2026-02-19 20:39:46.030864
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed9308d6cbfa'
down_revision: Union[str, None] = 'e66fe5abb7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('mrr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrr_currency', sa.String(length=3), nullable=False),
    sa.Column('arr', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrr_growth_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_revenue_currency', sa.String(length=3), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_expenses_mxn', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('burn_rate', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('runway_months', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('total_customers', sa.Integer(), nullable=False),
    sa.Column('new_customers', sa.Integer(), nullable=False),
    sa.Column('churned_customers', sa.Integer(), nullable=False),
    sa.Column('arpu', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ltv', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cac', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('open_tasks', sa.Integer(), nullable=False),
    sa.Column('overdue_tasks', sa.Integer(), nullable=False),
    sa.Column('prospects_in_pipeline', sa.Integer(), nullable=False),
    sa.Column('prospects_won', sa.Integer(), nullable=False),
    sa.Column('data_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpi_snapshots')
    # ### end Alembic commands ###
